### ISSUE TITLE
Assertion in CyclicModuleExecutionRejected is still invalid

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-top-level-await#102]
Consider A <-> B, B succeeds, A throws an exception. We will first call A.Evaluate() -> IME(A) -> ECM(A) -> CyclicModuleExecutionRejected(), then return back to A.Evaluate() with stack = [A, B], and since A is not the last element of the stack, we call CyclicModuleExecutionRejected() again.

**Comment by littledan** [comment]
I think you are right that this is a bug. This seems like the result of some of our phrasing of bookkeeping; I bet we will be able to find a small fix as we did for a couple other of these recently.

In the worst case, couldn't we bail out with a conditional rather than an assertion? I think we can find a cleaner solution, though.
