### ISSUE TITLE
What prevents GetCycleRoot from triggering for synchronous cycles?

### ISSUE THREAD

**Issue by joshualitt** [tc39/proposal-top-level-await#121]
Forgive me if I missed something in the specification, but I am trying to figure out how GetCycleRoot behaves in the presence of cycles such as in [this](https://github.com/tc39/test262/blob/master/test/language/module-code/instn-star-props-circular.js) 262 test.

In the linked test, Top depends on A and B, A depends on B, and B depends on A. During depth first traversal, Top evaluates A, which evaluates B. B tries to evaluate A, but A is already evaluating. B then takes on A as its DfsAncestor. When A finishes evaluating, A, being the root of the A/B cycle, now transitions A and B to evaluated and returns. Top calls GetCycleRoot on A, but this is safe as A is the root of its cycle. Top now tries to evaluate B, but B is already evaluated and thus Top calls GetCycleRoot(InnerModuleEvaluation 12.d.iv) on a synchronous module which is not the root of a cycle and which has no AsyncParentModules and the assert in GetCycleRoot at 2.a fires.

I fully admit I am probably misunderstanding something. What am I missing?

**Comment by guybedford** [comment]
You're exactly right here - this sounds like a bug in the assertion logic of GetCycleRoot to me.

The problem seems to be that we should really be calling `GetCycleRoot` `GetAsyncCycleRoot`, and change the assertions to instead break the entire iteration on the sync case - I've put together a PR along these lines at https://github.com/tc39/proposal-top-level-await/pull/122 although note that this fix still needs to be reviewed.
